### ISSUE TITLE
Add organisation-specific settings to configuration

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#101]
To super multiple deployments for multiple organisations from the same codebase. 

@bedrich-schindler please specify, what will be needed. The config does not need to be in admin, since it likely won't change.

**Comment by bedrich-schindler** [comment]
That depends on what different organizations need. But if we speak only about changing names, logos and configurations:

Client:

* Move static information (like DITT title) and logo into some `brand` folder
* Update webpack and node configuration to be able to build different brands (make DITT as default brand)
* Other brands would provide own brand folder with all necessary files before build, so they won't be part of this repository
* If another organisation is not part of DBJR, they would probably need to create own repository with own brand files and build configuration 

API:

* API already has `.env` configuration so the base configuration and naming is already ready
* Only things that might be customized are emails. It depends whether it is ok to have default emails or whether it is necessary to make it different for each organization
