### ISSUE TITLE
Dropdown selection of superiors

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#102]
Explanation: Since a few weeks (around September) the dropdown selection of supervisors does not work anymore. This feature is on the users' profile page. We have tried this on different browsers and computers and everywhere the problem exists. I manage for once that it works again when I clear the cache. But this is only possible after several attempts. Is the script outdated or something similar?

![Bug 1 selection superior]

**Comment by davidurban** [comment]
Temporary fixed on DBJR, caused by memory overflow.

**Comment by bedrich-schindler** [comment]
I optimized it using special endpoint for retrieving list of users, so page load is rapidly improved.
