### ISSUE TITLE
Listing of users is no longer displayed

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#103]
When calling the user overview, the listing does not appear anymore. But I manage to create the list by pressing the sorting arrows several times. But of course this is not a good permanent condition.

![Bug 2 user overview](https://user-images.githubusercontent.com/8739891/204453316-5bfc6230-9002-4bf5-8bb1-75842c3b77e1.JPG)

**Comment by davidurban** [comment]
Temporary fixed on DBJR, caused by memory overflow.

**Comment by bedrich-schindler** [comment]
Loading time was improved in #102 by changing serialization of `/users` endpoint. Now it does return only necessary data, deep nested structures are omitted now.

In #103, I split `/users` endpoint into two parts. Initially, only partial data about employees and their supervisors are loaded. It is quite fast. Asynchronously with this call, call for original endpoint is made and Arbeitzeitkonto + Urlaubskonto are loaded later:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/10213870/217849911-54d3f436-af80-4028-99e4-c269136382e5.png">
