### ISSUE TITLE
Add vacation days to "Supervised Users"

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#105]
At the moment the supervisors only see the plus/minus time budget an employee, but they should also see the vacation days (X/Y) like it's shown in "users" page.

**Comment by bedrich-schindler** [comment]
EN:

![image](https://user-images.githubusercontent.com/10213870/215712645-e4c7f06e-b4cd-4077-a5e8-3526f101be53.png)

DE:

![image](https://user-images.githubusercontent.com/10213870/215712780-46439a02-666e-4559-b1f6-a8d78d4900db.png)

---

To compare with other pages:

![image](https://user-images.githubusercontent.com/10213870/215715111-fbfa88f3-3c3a-419c-89fe-d79e26d452a3.png)

![image](https://user-images.githubusercontent.com/10213870/215715202-aed2d958-f6f4-46dc-be46-e83c5774278e.png)

![image](https://user-images.githubusercontent.com/10213870/215715272-71bd6434-76a6-4e89-bbfc-3f5ca5185174.png)

If the columns should be order another way, let me know.
