### ISSUE TITLE
Add "Sickness Last 365 days" from "Year overview" to Supervised users table

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#107]
Automatic view supervisor in case an employee had more than 30 sickdays in the past 365 days like the HR role can see it already. (GE legal requirement)

**Comment by bedrich-schindler** [comment]
@davidurban  Should I show real number of sickness in last 365 days or just only if there is 30 days or more in last 365 days? Title of this issue mentioning "Year overview" page that shows real number of those days ... Version in development looks like this:

<img width="1004" alt="sickdays" src="https://user-images.githubusercontent.com/10213870/215517084-18f1c677-3469-4347-b3c7-f934975bb9bc.png">

Beside that sickdays have 3 variants (with node, without node and sick child). I just copied two columns from "Year overview" to "Supervised users" page. If it should be done another way, let me know. I don't know which 30 days to count (whether it should include sick child or not)

**Comment by davidurban** [comment]
This is ok. We may need to iterate in case there is feedback, but I don't expect it.

**Comment by cetcondor** [comment]
Specification: After discussion between DBJR and AdB we would like to slightly adjust the feature: supervisors should only see the number if it is **over 30 days** for a specific employee. 
Reasoning is: supervisors are often mere team-leaders and not in role of the employer itself. So too much availability of accumulated data is not privacy-sensitive enough.

**Comment by davidurban** [comment]
@cetcondor the feature has been implemented 2 weeks ago. Should we create a new task for the proposed modification?

**Comment by davidurban** [comment]
Created https://github.com/DBJRdev/ditt-client/issues/114 to address the improvement.
