### ISSUE TITLE
Add notification of sick day

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#109]
Entering sick days should trigger email to HR role with at least following information: person name, start and end date, with or without note.

**Comment by davidurban** [comment]
@bedrich-schindler  I am sorry, we have just agreed with AdB and BDJR, that this needs to be switched on/off per instance. Could you please make the modification?

**Comment by davidurban** [comment]
Default: AdB on, DBJR off.

**Comment by bedrich-schindler** [comment]
And for BG?

**Comment by davidurban** [comment]
BG off

**Comment by bedrich-schindler** [comment]
Note for deployment:

⚠️ Update .env file with:

```
# Feature flags
FF_NOTIFICATIONS_SICK_DAY_WORK_LOG_CREATED=1'
```
