### ISSUE TITLE
Add "Sickness Last 365 days" from "Year overview" to Supervised users table – improvements

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#114]
> Specification: After discussion between DBJR and AdB we would like to slightly adjust the feature: supervisors should only see the number if it is over 30 days for a specific employee.
> Reasoning is: supervisors are often mere team-leaders and not in role of the employer itself. So too much availability of accumulated data is not privacy-sensitive enough.

Improves: https://github.com/DBJRdev/ditt-client/issues/107

**Comment by davidurban** [comment]
DBJR feedback:
The implementation is different from our request. I can see in Github also no other order from AdB, for our version please implement as follows:
Please remove the column child sick! A number should only appear if 30 sick days are reached. Otherwise "-"

**Comment by bedrich-schindler** [comment]
@davidurban Feedback is from DBJR, but it is labeled as AdB? So for who should I implement this change? Need this to be different for different instances?

**Comment by bedrich-schindler** [comment]
@davidurban @cetcondor

* I removed column sick child as requested
* I show number of sick days only if there are more than 30 sick days in last 365 days

What I want to double check is that until now we counted sick days with child as one column and without child as second column. As ADB requested, I just removed sick child row but I did not merge numbers - it was not specified. So it only includes sickdays without children. If it should include sick days with child (it means all sick day variants), just let me know, I will remove the filter.

I am closing it now, it change is requested, please re-open it with comment
