### ISSUE TITLE
Add a checkbox to indicate „Mobile Arbeit/Home office“ in normal Worklog?

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#117]
In the "Arbeitzeit/Working time" type, could we add a checkbox below where the employee indicates with the selection whether this time entry is „Mobile Arbeit/Home office“?
![Mobile Arbeit](https://user-images.githubusercontent.com/8739891/229522405-1369c87f-83ae-45db-a0a8-47b8c6757ce5.jpg)

This information should also have its own column in the csv export file #104, in which e.g. "yes" is written if the checkbox was clicked.

**Comment by bedrich-schindler** [comment]
Is this checkbox somehow related to „Mobile Arbeit/Home office“ work log or it is just a flag and there is no logic connection between them? Is this feature just for DBJR or can it be implemented for whole system? Is there any indication of such worklog on Monthly log page or need I to open detail of the worklog to see it?

**Comment by davidurban** [comment]
There is no relation, the checkbox is information only. Should appear in export, otherwise it has no bearing onto calculation or other features.
