### ISSUE TITLE
Change sender name for testing/dev environments 

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#126]
As Tim says:

> When using the DITT testing deployments, emails are triggered to
> supervisors and HR department. So far no problem. But it becomes a bit
> of a challenge for them to distinguish what is real and what is tests,
> because both emails from production and testing just look the same.
> 
> Simple proposal. Could you set a different real name/display name like
> “Zeit test <[zeit@adb.de](mailto:zeit@adb.de)>“, or a different email address for the test
> server? (whichever is easier).
> 
> It's not urgent, but as  I put and canceled lots of vacations, sickdays
> and business trips, my colleagues are a bit overwhelmed. 

Could we please make the change for all Dev environments?

**Comment by bedrich-schindler** [comment]
As ADB has self-hosted dev server, it was problem just with this instance. DITT, DBJR and BG is OK.

If @cetcondor wants, he can create email for development/beta environment and we can change it. We use different emails for each instance and each environment on our server, so production and dev/test/beta emails are explicitly different.
