### ISSUE TITLE
Script for backing up database is needed

### ISSUE THREAD

**Issue by DBJRdev** [DBJRdev/ditt-client#5]
For reasons of data safety, a script is needed to backup and download the database. (Providers may only backup for several days, but employee management is a longterm thing).

The backup script could be part of the HR account backend or a totally separate script, if there is a good reason for it (not sure).

**Comment by bedrich-schindler** [comment]
@DBJRdev @davidurban I would like to say that this seems to be critical part of whole system. I strongly recommend to complete issue assignment to be able to implement it as soon as possible.

**Comment by DBJRdev** [comment]
Sorry for the late response! Please implement an automatic backup functionality but add an option for de- / activating it to the user interface.

There should be two options:
1. Local backup
2. Backup on a remote server via SSH

The default should be a local backup.
If credentials for transferring the backups via SSH to another server are set via the user interface, the backups should not be stored locally.

**Comment by davidurban** [comment]
Thank you for letting us know!

I am not sure whether we can access ssh through PHP, but @bedrich-schindler will tell us :). I would expect us using server CRON to trigger the backup, using a standalone script. 

@DBJRdev Is it critical for you to have settings in DITT admin? Since the backup will work fairly independently on the system itself, it will add complexity. 

For local backups – how often should we create them? And how may to the past should be kept?

**Comment by davidurban** [comment]
We have concerns regarding adding the feature to the DITT web interface – it could lead to downloading the database (and all its private information) onto unauthorised computers. We would recommend creating a script, that would create a backup and the send it via ssh to a server of your choice. 

Please let me know, if omitting the feature in web interface is acceptable for you. 

To implement, we will need information about backup rotation strategy and server information, where we should send the backup (please send separately, not here :)).

**Comment by DBJRdev** [comment]
>  I would expect us using server CRON to trigger the backup, using a standalone script.

I do not know what is currently done with cron but we should better use systemd services since they can be managed relatively easy.

> @DBJRdev Is it critical for you to have settings in DITT admin? Since the backup will work fairly independently on the system itself, it will add complexity.

OK, then omit the setting in the web interface.

> For local backups – how often should we create them? And how may to the past should be kept?

I suggest to create one backup per day and keep them for two weeks.

> We have concerns regarding adding the feature to the DITT web interface – it could lead to downloading the database (and all its private information) onto unauthorised computers. We would recommend creating a script, that would create a backup and the send it via ssh to a server of your choice.

My suggestion was only to add a setting for enabling / disabling the automatic backup instead of a download option there.

**Comment by bedrich-schindler** [comment]
After discussion we had with @davidurban two weeks ago, I implemented cron routine that makes backup of database every midnight and removes backups older than 14 days. Backups are saved into `/usr/home/zeitfn/backup` directory. Backup directory can be changed using `crontab -e` (it is passed as first parameter to the backup script; if you change this directory, create this directory first).

If there is any request (like sending backups over ssh/rsync to some backup server) please let @davidurban know.
