### ISSUE TITLE
Use only time for entry of type *Kranktag* if set

### ISSUE THREAD

**Issue by DBJRdev** [DBJRdev/ditt-client#60]
Currently, an accepted entry of type *Kranktag* has no effect on the calculated time of a day if there are other entries for the same day. After adding an entry of type *Kranktag*, the calculated time (sum) for a day should always be the time for one day (e.g. 7 hours and 48 minutes) regardless if there are additional entries for that day.

Example for one day:
*Arbeitszeit* with 3 hours
*Arbeitszeit* with 2 hours
*Kranktag* with 7 hours and 48 minutes
=> sum for that day = 7 hours 48 minutes

**Comment by davidurban** [comment]
@DBJRdev could you please confirm calculation stated above? Co we can fix this issue?

**Comment by cetcondor** [comment]
According to the German “Gesetz über die Zahlung des Arbeitsentgelts an Feiertagen und im Krankheitsfall“ (~law about continuation of salary on holidays and in case of sickness) an employee has the legal right to receive full compensation when being sick, just as if they had worked to full extent. (A German explanation can be found here: https://www.haufe.de/personal/haufe-personal-office-platin/zeitkonten-richtig-gestalten-24-entgeltfortzahlung_idesk_PI42323_HI2350649.html)

For DITT that means that any additional worklog for a sickday needs to be ignored by DITT and a full working day needs to be taken into account.

**Comment by bedrich-schindler** [comment]
@davidurban When deployed, can you notify everybody about this change in calculation?

Before:
<img width="617" alt="Snímek obrazovky 2023-06-19 v 9 58 09" src="https://github.com/DBJRdev/ditt-client/assets/10213870/8853a47c-4224-4916-bfa3-9c01785d87dc">

<img width="1841" alt="Snímek obrazovky 2023-06-19 v 9 57 55" src="https://github.com/DBJRdev/ditt-client/assets/10213870/bf8e0c9b-da07-4c72-9f87-0af371a3e804">

After:

<img width="1842" alt="Snímek obrazovky 2023-06-19 v 10 00 30" src="https://github.com/DBJRdev/ditt-client/assets/10213870/e0c46727-f6ce-4f8c-88ff-0a516943fbf9">

**Comment by cetcondor** [comment]
Tested and works perfectly now!
