### ISSUE TITLE
Limit working time to two digits in the corresponding valid range

### ISSUE THREAD

**Issue by DBJRdev** [DBJRdev/ditt-client#61]
When entering a working time, it is currently possible to enter letters, more than two characters per field and input like `24` for hours or `60` for minutes. It should be limited to two digits in the corresponding valid range of `[0,23]` for hours and `[00,59]` for minutes instead. An additional error message as it is shown at the moment could be shown directly after entering a non-valid character.

Example:
Currently, you can enter `1abc : 12345` but it should be limited to `1 : 12`.

If the check for digits only or the range-based check is too complex, the limitation of two characters should be implemented at least.

**Comment by bedrich-schindler** [comment]
It is not written here but same inputs are in supervisor's view in Ban on working form and Work time correction form. I implemented those restrictions there as well. For Ban on working, I approved hours to be up to 999 because there could be greater values than 23 as we can see in production.
