### ISSUE TITLE
Show indicator if day has been recalculated automatically because of rules

### ISSUE THREAD

**Issue by DBJRdev** [DBJRdev/ditt-client#74]
As desired, DITT recalculates the daily working hours in case the employee's entry is not paying attention to obligatory breaks. Yet it would be very useful for the user to see a flag/asterisk or anything for the day, if DITT "did something" according to its internal ruleset.

**Comment by bedrich-schindler** [comment]
![image](https://user-images.githubusercontent.com/10213870/101751626-c2c17900-3ad0-11eb-8a1f-b6d39492f93f.png)

Icon `baseline_update_black` is not available
