### ISSUE TITLE
Add field that shows the current working hours status until (including) today

### ISSUE THREAD

**Issue by DBJRdev** [DBJRdev/ditt-client#77]
One of the main challenges we have with DITT is that our colleagues often don't know what their current status of working hours is (whether they have plus/minus hours).

The thing is that people have to wait until a month is acknowledged and then have a look at the following month, in order to know the status. Example: at the end of October, DITT does not tell me where I stand, but I need to have a look on the November page. And all the supervisors accepting things have to be fulfilled as well.

Therefore we would ask for the following feature:
**add a very visible field on the monthly page, which calculates a status of all hours until (=including) today**, as a preliminary information where the employee stands. It should update when I add or change the worklog for today or earlier days of this month.

a) If I worked 18 hours and 20 minutes more than I was supposed to, it should show:
```
Aktueller Stand (vorläufig): + 18:20 h
Current status (preliminary): + 18:20 h
```

b) If I worked less than required, it should show:
```
Akuteller Stand (vorläufig):  - 18:20 h
Current status (preliminary): - 18:20 h
```

**Important to be aware:** the status field should ignore any application for upcoming days or weeks. It should only show the status until (=including) today. Applications for days until today, which have not yet been accepted yet, should be treated as if they were valid already.

**Comment by davidurban** [comment]
**Approved Month** – add "Status at the end of May after approval: -10:45 h", to the bottom of the page. 

**Month in progress** – as Tim explained above; at the top display current total worked hours to of monthly hours (excluding any over/undertime). 
Add new "Current status" (calculate including current day, so in the morning there is for example "-8h", when I log 8h it says "0". It will be located in the next column after "6:00 h" only for today and moving. 

**Right side of sheet**: add "Difference from previous months: - 10:24h"

**Comment by davidurban** [comment]
At /supervised-users and /users please:

- delete "worked/required hours" and
- add "Status at the end of May after approval: -10:45 h" and "Current status"

**Comment by davidurban** [comment]
If there are complications "Current status" is not critical.

**Comment by bedrich-schindler** [comment]
Attaching images of improved calendar according to assignment from above:

![V1a](https://user-images.githubusercontent.com/10213870/126168891-9e81215f-305c-4ec5-a751-13f54c600198.png)

![V1b ](https://user-images.githubusercontent.com/10213870/126168918-5bad0609-e9f9-423b-bb7d-a90394c8dd5b.png)

![V2a](https://user-images.githubusercontent.com/10213870/126168930-931da250-a09f-4f62-8d3c-ffdb44dc660d.png)

![V2b](https://user-images.githubusercontent.com/10213870/126168944-1268c7cb-8760-4adf-b628-f2326f01d25a.png)

![V3a](https://user-images.githubusercontent.com/10213870/126168964-1c3ed567-8122-4144-a03a-9ec410586c3b.png)

![V3b](https://user-images.githubusercontent.com/10213870/126168983-f3c7819a-662e-4af1-9075-fa043d15e2d1.png)

**Comment by bedrich-schindler** [comment]
Monthly logs translations (see pictures above):

```
      "correction": "Correction by HR",
      "differenceFromPreviousMonth": "Difference from previous months: {{ hours }} h",
      "openedWorkMonth": "Dieser Monat erscheint leer, weil der/die Arbeitnehmer*in ihn noch nicht übermittelt hat.",
      "statusAtEndOfMonth": "Status at the end of the month after approval: {{ hours }} h",
      "workedHoursLeft": "({{ workedHours }} h left)",
      "workedHoursOvertime": "({{ workedHours }} h overtime)",
      "workedAndRequiredHours": "{{ workedHours }} h von {{ requiredHours }} h",
      "workedAndRequiredHoursDiffers": "{{ workedHours }} h von {{ requiredHours }} h (Angezeigt wird nur die Monatsarbeitszeit nach alter Berechnungsgrundlage. Tagessummen sind ausgeblendet.)"
    
```

Supervised users and users translations (see pictures below):

```
      "endMonth": "{{ time }} (<0>End {{ month }}</0>)",
      "endMonthStatus": "End of month status",
 ```

<img width="644" alt="image" src="https://user-images.githubusercontent.com/10213870/126315811-b5910ba7-3201-493c-b0f2-5f538c0a5c26.png">

**Comment by bedrich-schindler** [comment]
@davidurban @DBJRdev Could you please provide translated texts from previous comment?

**Comment by davidurban** [comment]
Cannot access Users page due to Access Control. @bedrich-schindler, could you please check it?

<img width="1008" alt="Screen Shot 2021-07-20 at 15 17 01" src="https://user-images.githubusercontent.com/8739891/126330813-501e80a4-ce14-40fe-a6ab-f378cbcc04d2.png">

**Comment by davidurban** [comment]
Can we please add explicit + or − to the previous month difference to make it clearer?

<img width="328" alt="Screen Shot 2021-07-20 at 15 19 24" src="https://user-images.githubusercontent.com/8739891/126331143-0e8ea13f-dff8-4318-b81e-5af6bb773481.png">

**Comment by davidurban** [comment]
(in the example above there should be − 6:48
<img width="409" alt="Screen Shot 2021-07-20 at 15 21 36" src="https://user-images.githubusercontent.com/8739891/126331352-6fb9b29b-a5cf-4f06-ae15-40a386c3b92e.png">

**Comment by davidurban** [comment]
Thanks! All good!
