### ISSUE TITLE
Fix builds causing errors in console

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#8]
CZ: Novější verze Docker image z nějakého důvodu buildují JS asi trochu jinak než doposud a v konzoli se objevuje chyba, která pravděpodobně nemá na fukčnost aplikace vliv, ale je potřeba ji odstranit

**Comment by bedrich-schindler** [comment]
I went through whole application to check for any console errors in current version of application in development. There are currently 3 warnings and 0 errors, but any all of them are displayed in production application, just development:

1. `/hr/year-overview` - `Warning: Failed prop type: Invalid prop columns[6].label of type object supplied to Table, expected string.` - This is OK, it is just incompatible check of ReactUI library.  Not visible in production mode.
3. `http://localhost:8080/users/profile` - This is OK, it is just incompatible check of ReactUI library. Not visible in production mode.
3. ` Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.` - This is unexpected, but it is OK. It would require to refactor whole WorkLogCalendar component to get rid of it.  Even though it is just infomational and safe.

Few accessability warnings were fixed
