### ISSUE TITLE
Holiday requests multiple users' merging

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#85]
For description, see email.

**Comment by bedrich-schindler** [comment]
I fixed reported problem.

Now only those work logs whose data are exactly the same are being collapsed (merged). Before it was not checking type of work log and its details so two different work logs might have been collapsed into one.

After e-mail discussion with @davidurban, I extended merging of work logs. Now all types of work logs are being merged on Special Approvals page so you can also approve, reject and acknowledge those work logs in bulk and you do not have to do those operations for Bussiness Trip, Home Office, Time Off, Overtime one by one. I should have been done when support for entering multi-days work logs was implemented but there was no such request for that. So it is done for all the same way.
