### ISSUE TITLE
Add worklog add +2 hours

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#87]
If I add normal worklog form 10:00 to 12:00, DITT logs 12:00 to 14:00.

If I try to duplicate that entry, every duplicate gets +2h everytime.

**Comment by bedrich-schindler** [comment]
I've checked it. Client use central europe time zone Europe/Prague which is equal to Europe/Berlin time zone. API is dependent on server configuration, so if server configuration differs, bug arrises. We should check timezone configuration on dev server in that case.

**Comment by davidurban** [comment]
Thank you! I'm closing here since it has been checked and no problem has been found.

**Comment by bedrich-schindler** [comment]
Timezone of dev server fixed.
