### ISSUE TITLE
Supervisor should not see "Users" page

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#88]
It may be a new bug, "Johny Morty" employee-admin@example.com sees "Users" pages. He should not see it. 

Could you please check and confirm?

**Comment by davidurban** [comment]
Supervisor should only see his supervised users. Not the "users" tab.

**Comment by bedrich-schindler** [comment]
According to original specification, we have 3 roles: employee, admin and super admin. Employee is only role that can se monthly calendar. Admin can manage users, but does not have his/her calendar. Difference between admin and super admin is that super admin role is being assigned to HR people who are able to see HR specific pages and Settings page which standard admin cannot see. Admin can 

employee-admin@example.com has two roles: employee and admin, so he/she should be able to manage its monthly logs and users as well. So it should be correct.

Supervisor is not a role. Supervisor can be either employee or admin. Supervisor is person that is set in profiles of other employees. So if any employee has set XYZ as supervisor, than XYZ is supervisor.

**Comment by davidurban** [comment]
Thank you for the confirmation, closing.
