### ISSUE TITLE
Add translation 2021-07-23

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#89]
Please add translations and respond to questions by DBJR:

"correction": "Correction by HR":
Translation: Korrektur durch Personalbereich
"differenceFromPreviousMonth": "Difference from previous months: {{ hours }} h",
Translation: Übertrag aus Vormonat
"openedWorkMonth": "Dieser Monat erscheint leer, weil der/die Arbeitnehmer*in ihn noch nicht übermittelt hat.",
Do you need a translation here? Or a better one? Than: Monat noch nicht durch Arbeitnehmer*in eingereicht.

"statusAtEndOfMonth": "Status at the end of the month after approval: {{ hours }} h",
Translation: Stundenstand nach Freigabe
Layout: Can we do this to the right?
Can we please add here also explicit + or − to make it clearer?
Question: Will this status be unchangeable after approval?
Or does it count additional approvals? I had the case that an earlier month was completed/approved later. So if there are additional approvals/edits before the current month, they have to be added here. Does it do that?

Please do not write anything after the time for now.
"workedHoursLeft": "({{ workedHours }} h left)",
"workedHoursOvertime": "({{ workedHours }} h overtime)",
Can we please add here also explicit + or − to make it clearer if it ist overtime or minushours?

I am not sure here for what a translation?
"workedAndRequiredHours": "{{ workedHours }} h von {{ requiredHours }} h",
Translation: geleistete Stunden von erforderliche Stunden
"workedAndRequiredHoursDiffers": "{{ workedHours }} h von {{ requiredHours }} h (Angezeigt wird nur die Monatsarbeitszeit nach alter Berechnungsgrundlage. Tagessummen sind ausgeblendet.)"

Supervised users and users translations:
 "endMonth": "{{ time }} (<0>End {{ month }}  </0>)",
translation: Ende
 "endMonthStatus": "End of month status":
translation: Stand Arbeitzeitkonto

**Comment by bedrich-schindler** [comment]
> "openedWorkMonth": "Dieser Monat erscheint leer, weil der/die Arbeitnehmerin ihn noch nicht übermittelt hat.",
Do you need a translation here? Or a better one? Than: Monat noch nicht durch Arbeitnehmerin eingereicht.

I just copy pasted whole block of translation to show you the context in which are other translations placed. Not necessary to change it.

> "statusAtEndOfMonth": "Status at the end of the month after approval: {{ hours }} h",
Translation: Stundenstand nach Freigabe
Layout: Can we do this to the right?
Can we please add here also explicit + or − to make it clearer?
Question: Will this status be unchangeable after approval?
Or does it count additional approvals? I had the case that an earlier month was completed/approved later. So if there are additional approvals/edits before the current month, they have to be added here. Does it do that?

It is implemented according to assignment from @davidurban, so it just simply takes required hours, subtracts worked hours from that and that is status at the end of month. So anything that changes either required hours or worked hours changes also this status. Generally, anything could be changed until work month is approved.

> Please do not write anything after the time for now.
"workedHoursLeft": "({{ workedHours }} h left)",
"workedHoursOvertime": "({{ workedHours }} h overtime)",
Can we please add here also explicit + or − to make it clearer if it ist overtime or minushours?

@davidurban I am afraid it would confuse users as there will be two times without context. Left/overtime is important here -at least  in my opinion. Can you confirm this before I change it?

> I am not sure here for what a translation?
"workedAndRequiredHours": "{{ workedHours }} h von {{ requiredHours }} h",
Translation: geleistete Stunden von erforderliche Stunden
"workedAndRequiredHoursDiffers": "{{ workedHours }} h von {{ requiredHours }} h (Angezeigt wird nur die Monatsarbeitszeit nach alter Berechnungsgrundlage. Tagessummen sind ausgeblendet.)"

Same as above. Just posted whole block of translations to show you context.

**Comment by davidurban** [comment]
@bedrich-schindler please leave "left/overtime" for now. We can easily bring it back and it may be more clear with just +/-. Please deploy new DE translations to staging.
