### ISSUE TITLE
Improve printing by making unnecessary elements invisible

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#95]
Improve printing styles to get rid of UI components and make monthly report printing from browser possible.
[DITT getting rid of menu buttons for printing.pdf](https://github.com/DBJRdev/ditt-client/files/8876517/DITT.getting.rid.of.menu.buttons.for.printing.pdf)

**Comment by bedrich-schindler** [comment]
Example of monthly logs export:

[Monthly logs print.pdf](https://github.com/DBJRdev/ditt-client/files/10664120/Monthly.logs.print.pdf)

If requested, further pages can be optimized for print. Just create new issues with required layout of the print. For now, header, footer, body title is removed from the printable output. Background is without paddings, margins and its background is set to white.

**Comment by davidurban** [comment]
Feedback from DBJR:
It's already closed, but the title "Monthly overview for NAME" / Monatsübersicht für XXXX and title "DBJR Digitale Zeiterfassung" are now missing. That would be important that this is still in the printout. Please note that the title of the other organizations is different. Button "Export" can also be out in the print version!
