### ISSUE TITLE
"Archiving" of inactive user accounts.

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#97]
When accounts should no longer be active, we want to move them to an seperate area, like an archive page. The overview page, where all users for the personnel area are displayed, is currently overflowing. The goal is a page/view of all active user accounts and from there a sub-section for the inactive user accounts. Or that you can jump between the views by choosing to show active user accounts (by default), show inactive accounts and have the option to show all accounts.

**Comment by davidurban** [comment]
> Bug: The function "Delete user" does not work (button in the user profile). There should also be a security query installed before the final deletion. A query like: "Do you really want to delete the user account?" And then confirm again.

"Delete" will be changed for "Archive", keeping the data in database.

**Comment by davidurban** [comment]
Support re-activation.

**Comment by davidurban** [comment]
Support deleting user and all its data from the Archive.

**Comment by bedrich-schindler** [comment]
How to display archived users in other listings? There are many HR pages where users are listed. Should we hide them or whaat to do with them? There are several pages with users listed and I am not sure whether we want to have all those pages split for active/inactive users and at the same time, we cannot hide them because their entries can participate in year overview. So what to exactly do with it?

**Comment by davidurban** [comment]
@DBJRdev we suggest using "contract" information for display and automatic "archive" functions. On HR lists we will display only employees with active contracts. Those without active contract cannot log on and can be seen on different section in Users tab where a new contract can be added. 

Is blocked by: #96

**Comment by davidurban** [comment]
Correction: 

- archiving will be manual, on user detail page – button with confirmation
- it should be possible to see archived users on "Year overview" and "Changes" pages – by selecting checkbox "show archived users"
