### ISSUE TITLE
New request type "Training" and worklog type modifications

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#99]
New request type "Training" as for "Business trip", with fields for entering date and contents.

**Comment by DBJRdev** [comment]
German translation for this request type is „Fortbildung“

add
- entry date (from – to) 
- a text entry field with headline ‚Title‘ in german ‚Titel‘
- a 2nd text entry field for a description with headline ‚Coment‘ in german ‚Kommentar‘
**Please note:** Do not add automatic working time!

**Comment by davidurban** [comment]
Add:
Adjust request type „special leave/sonderurlaub“: add a text entry field and with headline: „Reason of special leave“ german: Grund für Sonderurlaub

And:
adjust request type „Home office“ and „Business trip“: removing the automatic addition of the daily target working time. Adding an entry option of time (e.g. 10:00h as with the working time entry.)
However, without another calculation/influence on the calculation, only as Information!
Heading 'planned start/german: geplanter Beginn' and 'planned end/german: geplantes Ende'.

**Comment by davidurban** [comment]
> removing the automatic addition of the daily target working time. 
Add ability to switch on/off per installation.

**Comment by bedrich-schindler** [comment]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/10213870/216365460-88369d31-ea95-4cdd-a2fb-847670afe7ee.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/10213870/216365365-f2fc46e7-aac7-4b0a-b99c-ac645bad761a.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/10213870/216365560-59ba63fd-0f8e-403d-bea9-9db4b963b032.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/10213870/216365666-4a4ffe0a-e203-4b00-88ce-92e0cc31582e.png">

---

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/10213870/216366010-6bf269b3-cdc5-46cf-83d5-6826a4423fd9.png">

---

**Comment by bedrich-schindler** [comment]
Calculation of business trip, home office and training from "now" on:

<img width="1791" alt="calc" src="https://user-images.githubusercontent.com/10213870/216370497-1d8e8e60-733f-4f9e-9698-00c68ba90f7c.png">

**Comment by davidurban** [comment]
Corrections:

1. For "Business trip": do not remove the automatic addition of the daily target working time.
2.Remove adding an entry option of time by both request types „Home office“ and „Business trip“

**Comment by davidurban** [comment]
@bedrich-schindler please have a look at the changes in the last comment and implement them.

**Comment by davidurban** [comment]
Please fix 1.
I will follow-up about 2 and create a separate issue if need be
